---
- name: Add Nethesis - updates repository
  yum_repository:
    name: nethesis-updates
    description: Nethesis - updates
    baseurl: http://packages.nethesis.it/nethserver/enterprise/\$releasever/nethesis-updates/\$basearch
    gpgcheck: false
    enablegroups: true
    enabled: "{{ repositories_enabled }}"
    http_caching: none

- name: Add Nethesis - testing repository
  yum_repository:
    name: nethesis-testing
    description: Nethesis - testing
    baseurl: http://packages.nethesis.it/nethserver/enterprise/\$releasever/nethesis-testing/\$basearch
    gpgcheck: false
    enablegroups: false
    enabled: "{{ repositories_enabled }}"
    http_caching: none
